### ISSUE TITLE
Breaks in Mac Terminal on OS X 10.10.2

### ISSUE THREAD

**Issue by tdlm** [KeyboardFire/mkcast#16]
Not sure if you're worried about Mac at this point, but I get the following error when running the specified command on OS X 10.10.2:

``` bash
$ sudo ./setup.sh
$ newcast
xdpyinfo:  unable to open display "/private/tmp/com.apple.launchd.a93K09UjyA/org.macosforge.xquartz:0".
/usr/local/bin/mkcast: line 57: wmctrl: command not found
/usr/local/bin/mkcast: line 59: /2-/2: syntax error: operand expected (error token is "/2-/2")
/usr/local/bin/mkcast: line 60: -: syntax error: operand expected (error token is "-")
/usr/local/bin/mkcast: line 61: wmctrl: command not found
$ readlink: illegal option -- f
usage: readlink [-n] [file ...]
kill: 86355: No such process
```

After this, it just waits forever and nothing happens. I'm guessing this because wmctrl is for X Windows, but I felt like I'd post here to show my support for mkcast and to show interest on the Mac side.

**Comment by morenoh149** [comment]
:+1: osx

**Comment by nickdesaulniers** [comment]
+1 would use on OSX

**Comment by tckmn** [comment]
OS X support is not currently planned.

**Comment by morenoh149** [comment]
surely we can investigate how hard it would be to add support. Then determine if it's too hard and say it's not supported. @nickdesaulniers @tdlm What wmctrl features are used? if it's just window positioning there are other solutions http://superuser.com/questions/679149/is-there-any-wmctrl-alternatives-on-os-x

I'm not a fan of applescript but have been fiddling with it since yosemete added [javascript for automation support](http://developer.telerik.com/featured/javascript-os-x-automation-example/)

you could install wmctrl via brew via the x-11 homebrew tap https://github.com/Homebrew/homebrew-x11

if I get it working I'll report back :8ball:

**Comment by tdlm** [comment]
@morenoh149 

So I installed wmctrl via homebrew and attempted to run it again.

``` bash
➜  ~  newcast
xdpyinfo:  unable to open display "/private/tmp/com.apple.launchd.a93K09UjyA/org.macosforge.xquartz:0".
Cannot open display.
/usr/local/bin/mkcast: line 59: /2-/2: syntax error: operand expected (error token is "/2-/2")
/usr/local/bin/mkcast: line 60: -: syntax error: operand expected (error token is "-")
Cannot open display.
readlink: illegal option -- f
usage: readlink [-n] [file ...]
➜  ~  kill: 289: No such process
```

Obviously there's no magic bullet for this one. I think you're right about needing to use AppleScript unfortunately.

**Comment by morenoh149** [comment]
@tdlm what's that trying to do? open xquartz?

here's the output of `xpdyinfo` on my machine https://gist.github.com/morenoh149/f5a72da5b9ead46bc3e4 if you look at the bottom I also run the `grep dimension`.

The regex here https://github.com/KeyboardFire/mkcast/blob/ece3dba8480ea218106b03b5ef6fe746aa1a1c90/mkcast#L55 could be modified to get the dimensions correctly. @KeyboardFire what is the output of `xdpyinfo | grep dimensions` on a typical linux machine. Once we compare we can change the regex to get the right info.

**Comment by morenoh149** [comment]
@tdlm @nickdesaulniers could you test this line works on your machine `echo '    dimensions:    1440x877 pixels (381x232 millimeters)' | awk '{print $2}'` if so I'll submit a pull request

**Comment by morenoh149** [comment]
lol this'll never work on osx due to the dependency on `gnome-terminal`. It was fun diving into xquartz anyway. @tdlm I got output from `wmctrl` but you need to run it within a terminal that's launched by xquartz 
![screenshot 2015-02-06 21 10 34](https://cloud.githubusercontent.com/assets/587438/6090915/a3ec61ee-ae44-11e4-99f8-22db718fcfa3.png)

**Comment by tdlm** [comment]
@morenoh149 Bummer, but thank you for looking into that.

**Comment by morenoh149** [comment]
yeah not sure how this software works but my guess is it finds the window and targets some screen capturing software. Then translates the video to a gif.

Would be cool to make gifs from the output of http://unixhelp.ed.ac.uk/CGI/man-cgi?script Not sure if it's possible.

update: uses [Byzanz-record](http://www.linuxers.org/article/byzanz-record-record-your-desktop-session-gif-image) so it's screen to gif directly.
